stages:
  - deploy

deploy-job:
  stage: deploy  
  environment: production
  script:
    - cd /home/ubuntu/projects/react-forum-v2/
    - cd /home/ubuntu/projects/react-forum-v2/back-django/
    - source env/bin/activate
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - python3 manage.py collectstatic --noinput
    - cd /home/ubuntu/projects/react-forum-v2/front-react/
    - npm install
    - npm run build --prod
    - sudo systemctl restart gunicorn
    - sudo systemctl restart nginx

