# Generated by Django 4.1.1 on 2022-12-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='call_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='call_token',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='message',
            name='type_message',
            field=models.CharField(choices=[('DM', 'Chat'), ('CL', 'Call'), ('IMG', 'Image')], default='DM', max_length=3),
        ),
    ]
