# Generated by Django 4.0.4 on 2022-06-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_update',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
