# Generated by Django 4.1.1 on 2022-12-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_message_call_name_message_call_token_message_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='call_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='call_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
